repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.23.0"
    hooks:
      - id: terraform-docs-go
        name: "Glue terraform module docs"
        args: ["-c", "tf/glue/.terraform-docs.yaml", "markdown", "tf/glue"]
      - id: terraform-docs-go
        name: "Glue terraform module docs"
        args: ["-c", "tf/glue/.terraform-docs.yaml", "markdown", "tf/workflow_orchestrator/modules/batch"]
      - id: terraform-docs-go
        name: "Glue terraform module docs"
        args: ["-c", "tf/glue/.terraform-docs.yaml", "markdown", "tf/workflow_orchestrator/modules/buckets"]
      - id: terraform-docs-go
        name: "Glue terraform module docs"
        args: ["-c", "tf/glue/.terraform-docs.yaml", "markdown", "tf/workflow_orchestrator/modules/metadata-service"]
      - id: terraform-docs-go
        name: "Glue terraform module docs"
        args: ["-c", "tf/glue/.terraform-docs.yaml", "markdown", "tf/workflow_orchestrator/modules/ui"]
      - id: terraform-docs-go
        name: "Glue terraform module docs"
        args: ["-c", "tf/glue/.terraform-docs.yaml", "markdown", "tf/workflow_orchestrator/iam"]
      - id: terraform-docs-go
        name: "Glue terraform module docs"
        args: ["-c", "tf/glue/.terraform-docs.yaml", "markdown", "tf/workflow_orchestrator/infrastructure"]
